# Generated by Django 5.1.15 on 2026-05-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carrier_remove_product_brand_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='card_number',
            field=models.CharField(blank=True, help_text='Формат: 0000 0000 0000 0000', max_length=20, null=True, verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True, verbose_name='Аватар (путь)'),
        ),
    ]
