# Generated by Django 4.2.15 on 2026-04-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('standard', 'Стандартная (3-5 дней)'), ('express', 'Экспресс (1-2 дня)'), ('premium', 'Премиум (в день заказа)'), ('pickup', 'Самовывоз со склада')], default='standard', max_length=20, verbose_name='Способ доставки'),
        ),
    ]
