# Generated by Django 5.2.14 on 2026-05-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_brand_remove_product_carrier_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
