# Generated by Django 4.2.15 on 2026-04-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='supplyitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='supplyitem',
            name='supply',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='client',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='order',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.DeleteModel(
            name='SupplyItem',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
